name: Jenings Osteopathy
favicon: null
layout_spectrum: 0.24145163875073195
typography_spectrum: 0.41728950408287346
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5dade'
    - '#594d41'
    - '#827564'
    - '#ab9f89'
    - '#332b28'
  brandStrength: 0.6627680680248886
  lightness: 0.776824755826965
  saturation: 0.061093339463695884
  rhythmicContrast: 0.5029429527930915
purpose: []
